engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - public/**
  - src/**
  - "**.js"
exclude_paths:
  - Gruntfile.js
