language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
services:
- mongodb
before_install:
- gem install compass
- npm install -g grunt-cli bower
install:
- npm install
- bower install
branches:
  only:
  - master
env:
  matrix:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token:
      secure: 8AcKpO2S/bSuuAkL+p+9TjMbN4NLUpP14i15krBOpn6XXGdqe+dk+omE5m11HzNcHoriCojYdGw3f1pae95Dy2veswki+36B2rcXA/Y0JH8zZ9H1DjBpPzA5M/6Sgm++e9cr3yWigd/fMwZQ/9xrj6kw3edclNVGuSocNH1CB6hovUZq/vcj2gMVafIZYQu/6Z78YzAEoMzFIOt5vOy1aKWQEeaRsp/LskLwSEUm33nnD4HtP3hjInflAlsIimEIHEwWL7hox2p7M5sK/LhsUeuRhYtl5eSGBm89vi0QccpsbBcIAq6QHrc3YYouwORskzaiesiz3pyJCQP84joIm1Pd1Oc5QOuDpGoO9cfTwUP043WfXOi/BkRq1DBIeMq3MMkrTeq+FbOn2kAMEQasjBMBwLIUtuaZBWbiYqc9jlW2w87Lic17dIO9VXMYA3H13omHOGxd4FWTgVnTqalnVL5j/rRnyKUZGi/kFxImI1yHTlKQ1NZIDy9QTZI/V0eyG7eT3ftjaO5GlOLJ07bOI/+zXhSVTOccQta0UDHOYrxfAQLO/V2wD34f1hn6yvDTuJOTkMBn/u3QOJUxxH6KW0OBmFtJW8RxgNzS60oi7JC9M8Lvt6ZwiDAro+Fal2TZSG9prVqJ3oINcTiu4M63eM3ndYusGBvWQ8c0KppRC6I=
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ruby-dev
    - g++-4.8
