language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
services:
  - mongodb
before_install:
  - gem install compass
  - npm install -g grunt-cli bower
install:
  - npm install
  - bower install
branches:
  only:
    - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ruby-dev
      - g++-4.8
