language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
services:
- mongodb
before_install:
- gem install compass
- npm install -g grunt-cli bower istanbul codeclimate-test-reporter
install:
- npm install
- bower install
after_script:
- codeclimate-test-reporter < 'coverage/PhantomJS 2.1.1 (Linux 0.0.0)/lcov.info'
branches:
  only:
  - master
env:
  matrix:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: 4307ce2a974dae6dc62c4f3f73478690c2f1613ad18369b52c344b060638a47b
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ruby-dev
    - g++-4.8
